@server=http://localhost:8080/api

GET {{server}}/users/

###

GET {{server}}/users/Ebanx3

###

POST {{server}}/auth/signup
Content-Type: application/json

{
    "username":"Ebanx2",
    "password":"assssaaaX4",
    "email":"esteban2santos@gmail.com"
}

### 

POST {{server}}/auth/login
Content-Type: application/json

{
    "username":"Ebanx3",
    "password":"asdasdX$",
}